### PR TITLE
reduce lines

### PR DESCRIPTION
**Pull request by signorrayan**
Using dictionary and one-line print statements and for loops.

### CODE REVIEW

**Comment by adulau** [comment]
Good point. Thanks for pull-request.

**Comment by adulau** [comment]
I'll update it a bit to be sure to output a CSV as foreseen

**Comment by adulau** [comment]
Updated in fb0564e0c53642318ea7a16524ab2c9e295a8598 to keep the CSV output as used by other tools

**Comment by signorrayan** [comment]
> I'll update it a bit to be sure to output a CSV as foreseen

Thank you. i didn't know the comma seprated output is for CSV purpose and changed it to `: `

**Pull request merged**
